/**
 * Created by KMACIAZE on 01.10.2015.
 */

module.exports = {
     UsernameStringKeyFormData : 'mobile',
     PinStringFormKeyData : 'pin',
     ActionStringKeyFormData : 'action',
     ActionLoginStringValueForm : 'login',
     AccountUrl : 'https://nextbike.net/pl/m/home',
     LoginSuccessfulRecognizer: 'pl/m/logout',
     AccountHistoryRecognizer: 'data-role="list-divider"',
     RightCookieRecognizer: 'parameters[dlkey]',
     stationsNameNumberMap : {
          'Pl. Kromera': 5901,
          'Dworzec Nadodrze': 5904,
          'Politechnika Wroc³awska - Gmach G³ówny': 5935,
          'FAT - Grabiszyñska - Hallera': 5955,
          'Grabiszyñska - Stalowa': 5952,
          'Grochowa - Jemio³owa': 5958,
          'Hallera - Odkrywców': 5956,
          'Centrum Handlowe Borek': 5962,
          'Krucza - Mielecka': 5957,
          'Pereca - Grabiszyñska': 5951,
          'Zaporoska - Gajowicka': 5954,
          'Zaporoska - Grabiszyñska': 5943,
          'Zaporoska - Wielka': 5959,
          '¯elazna - Pereca': 5953,
          'Legnicka - Wejherowska': 5928,
          'Smoluchowskiego - £ukaszewicza': 5934,
          'Uniwersytet Wroc³awski - Joliot Curie': 5931,
          'Nowowiejska - Prusa': 5912,
          'Plac Grunwaldzki - Polaka': 5932,
          'Sienkiewicza - Piastowska': 5916,
          'Sienkiewicza - Wyszyñskiego': 5915,
          'Mickiewicza - pêtla tramwajowa': 5936,
          'Wyszyñskiego - Prusa': 5911,
          'Komandorska - Kamienna': 5963,
          'Powstañców Œl¹skich - Hallera': 5967,
          'Œlê¿na - Kamienna': 5964,
          'Koœciuszki - Komuny Paryskiej/Zgodna': 5948,
          'Traugutta - Koœciuszki': 5949,
          'Traugutta - Pu³askiego': 5942,
          'Dworzec kolejowy - po³udnie': 5950,
          'Koœciuszki - Pu³askiego': 5947,
          'Drobnera - Dubois': 5914,
          '¯eromskiego - Kluczborska': 5909,
          'Plac Bema': 5913,
          'Nowowiejska - Wyszyñskiego': 5910,
          'Plac Staszica': 5906,
          'Plac Uniwersytecki': 5917,
          'Jednoœci Narodowej - Nowowiejska': 5903,
          'Wita Stwosza - Szewska': 5921,
          'Teatralna - Piotra Skargi': 5941,
          'Jednoœci Narodowej - Oleœnicka': 5908,
          'Jednoœci Narodowej - Wyszyñskiego': 5902,
          'Bajana - Szybowcowa': 5907,
          '¯eromskiego - Daszyñskiego': 5905,
          'Teki': 5937,
          'Inowroc³awska - Urz¹d Skarbowy': 5924,
          'Dworzec kolejowy - pó³noc': 5946,
          'Plac Nowy Targ': 5920,
          'Armii Krajowej - Borowska': 5968,
          'Krynicka': 5969,
          'Gliniana - Gajowa': 5965,
          'Park Po³udniowy - Powstañców Œl¹skich': 5960,
          'Rac³awicka - Rymarska': 5970,
          'Skarbowców - Wietrzna': 5945,
          'Strzegomska - Gubiñska': 5929,
          'Rondo Reagana': 5933,
          'Arena - Komandorska': 5961,
          'Kamienna - Gajowa': 5966,
          'Arkady': 5972,
          'Skytower': 5971,
          'Hala Targowa': 5918,
          'Rynek': 5922,
          'Jana Paw³a II': 5923,
          'Zachodnia - Poznañska': 5925,
          'Plac Strzegomski': 5926,
          'Dworzec Miko³ajów': 5927,
          'Muzeum Narodowe': 5930,
          'Olszewskiego - Spó³dzielcza': 5938,
          'Plac Legionów': 5939,
          'Œwidnicka - Chrobry': 5940,
          'Œwidnicka - Pi³sudskiego': 5944,
          'Kredka i O³ówek': 5919,
          'Promenady Business Park': 5973
     }
};