/**
 * Created by KMACIAZE on 01.10.2015.
 */

module.exports = {
     UsernameStringKeyFormData : 'mobile',
     PinStringFormKeyData : 'pin',
     ActionStringKeyFormData : 'action',
     ActionLoginStringValueForm : 'login',
     AccountUrl : 'https://nextbike.net/pl/m/home',
     AccountHistoryUrl: 'https://nextbike.net/pl/m/account',
     LoginSuccessfulRecognizer: 'pl/m/logout',
     AccountHistoryRecognizer: 'data-role="list-divider"',
     RightCookieRecognizer: 'parameters[dlkey]',
     stationsNameNumberMap : {
          'Pl. Kromera': 5901,
          'Dworzec Nadodrze': 5904,
          'Politechnika Wrocławska - Gmach Główny': 5935,
          'FAT - Grabiszyńska - Hallera': 5955,
          'Grabiszyńska - Stalowa': 5952,
          'Grochowa - Jemiołowa': 5958,
          'Hallera - Odkrywców': 5956,
          'Centrum Handlowe Borek': 5962,
          'Krucza - Mielecka': 5957,
          'Pereca - Grabiszyńska': 5951,
          'Zaporoska - Gajowicka': 5954,
          'Zaporoska - Grabiszyńska': 5943,
          'Zaporoska - Wielka': 5959,
          'Żelazna - Pereca': 5953,
          'Legnicka - Wejherowska': 5928,
          'Smoluchowskiego - Łukaszewicza': 5934,
          'Uniwersytet Wrocławski - Joliot Curie': 5931,
          'Nowowiejska - Prusa': 5912,
          'Plac Grunwaldzki - Polaka': 5932,
          'Sienkiewicza - Piastowska': 5916,
          'Sienkiewicza - Wyszyńskiego': 5915,
          'Mickiewicza - pętla tramwajowa': 5936,
          'Wyszyńskiego - Prusa': 5911,
          'Komandorska - Kamienna': 5963,
          'Powstańców Śląskich - Hallera': 5967,
          'Ślężna - Kamienna': 5964,
          'Kościuszki - Komuny Paryskiej/Zgodna': 5948,
          'Traugutta - Kościuszki': 5949,
          'Traugutta - Pułaskiego': 5942,
          'Dworzec kolejowy - południe': 5950,
          'Kościuszki - Pu�askiego': 5947,
          'Drobnera - Dubois': 5914,
          'Żeromskiego - Kluczborska': 5909,
          'Plac Bema': 5913,
          'Nowowiejska - Wyszyńskiego': 5910,
          'Plac Staszica': 5906,
          'Plac Uniwersytecki': 5917,
          'Jedności Narodowej - Nowowiejska': 5903,
          'Wita Stwosza - Szewska': 5921,
          'Teatralna - Piotra Skargi': 5941,
          'Jedności Narodowej - Oleśnicka': 5908,
          'Jedności Narodowej - Wyszyńskiego': 5902,
          'Bajana - Szybowcowa': 5907,
          'Żeromskiego - Daszyńskiego': 5905,
          'Teki': 5937,
          'Inowrocławska - Urzad Skarbowy': 5924,
          'Dworzec kolejowy - północ': 5946,
          'Plac Nowy Targ': 5920,
          'Armii Krajowej - Borowska': 5968,
          'Krynicka': 5969,
          'Gliniana - Gajowa': 5965,
          'Park Południowy - Powstańców Śląskich': 5960,
          'Racławicka - Rymarska': 5970,
          'Skarbowców - Wietrzna': 5945,
          'Strzegomska - Gubińska': 5929,
          'Rondo Reagana': 5933,
          'Arena - Komandorska': 5961,
          'Kamienna - Gajowa': 5966,
          'Arkady': 5972,
          'Skytower': 5971,
          'Hala Targowa': 5918,
          'Rynek': 5922,
          'Jana Pawła II': 5923,
          'Zachodnia - Poznańska': 5925,
          'Plac Strzegomski': 5926,
          'Dworzec Mikołajów': 5927,
          'Muzeum Narodowe': 5930,
          'Olszewskiego - Spółdzielcza': 5938,
          'Plac Legionów': 5939,
          'Świdnicka - Chrobry': 5940,
          'Świdnicka - Piłsudskiego': 5944,
          'Kredka i Ołówek': 5919,
          'Promenady Business Park': 5973
     }
};